<Project>
  <Import Project="$(RepoRoot).props/*Packages.props" />
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AdHoc.Results.Abstractions" Version="$(Version)" />
    <PackageVersion Include="AdHoc.Results.HTTP.Abstractions" Version="$(Version)" />
    <PackageVersion Include="AdHoc.Results" Version="$(Version)" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="AdHoc.Build.VersionTags" Version="1.1.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="1.1.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.12.48" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
