<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <IsAotCompatible>false</IsAotCompatible>
    <NoWarn>$(NoWarn);NU5104</NoWarn>
    <IsPackable>true</IsPackable>

    <!--<PublishAot>true</PublishAot>
		<PublishTrimmed>true</PublishTrimmed>
		<TrimMode>full</TrimMode>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="AdHoc.Results.Abstractions" />
    <Using Include="AdHoc.Results" />
    <Using Include="AdHoc.Results.Result" Static="true" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AdHoc.Results.Abstractions/AdHoc.Results.Abstractions.csproj" />
    <ProjectReference Include="../../src/AdHoc.Results/AdHoc.Results.csproj" />
    <ProjectReference Include="../../src/AdHoc.Results.AspNetCore.OpenApi/AdHoc.Results.AspNetCore.OpenApi.csproj" />
    <ProjectReference Include="../../src/AdHoc.Results.SourceGenerators/AdHoc.Results.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  
  <Target Name="DefineAOTConstants" BeforeTargets="BeforeCompile">
    <PropertyGroup Condition="'$(PublishAot)' == 'true'">
      <DefineConstants>$(DefineConstants);AOT</DefineConstants>
    </PropertyGroup>
  </Target>
</Project>
