<Project>
  <Target Name="_RemoveNetStandardFromExe" BeforeTargets="Build" Condition="'$(OutputType)' == 'Exe'">
    <PropertyGroup>
      <TargetFrameworks>$([System.Text.RegularExpressions.Regex]::Replace($(TargetFrameworks), ';?netstandard[^;]*', ''))</TargetFrameworks>
    </PropertyGroup>
  </Target>
</Project>
